export const strings = {
  brandName: 'Currency Converter',
  pageTitle: 'Convert Czech Koruna',
  pageSubtitle: 'Enter an amount and choose a currency to convert to.',
  filterPlaceholder: 'Search currency...',
  listHint: 'Tap a currency to convert',
  loading: 'Loading rates...',
  error: 'Rates are currently unavailable. Retrying...',
  retry: 'Retry',
  noRates: 'No rates available.',
  noMatch: 'No currencies match your search.',
  ratesAsOf: 'Rates as of',
  labelFrom: 'From',
  labelTo: 'To',
} as const
